"""Render the configuration the live stack needs.

The demo's Prometheus config has no `rule_files` and no `alerting` block, so
Firebreak adds both. Rather than keeping a copy of the upstream config, which
would drift the next time the pin moves, the file is generated from the
vendored one every time the stack starts.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

RULE_FILE_IN_CONTAINER = "/etc/prometheus/firebreak-alert-rules.yml"
ALERTMANAGER_TARGET = "alertmanager:9093"
GENERATED_HEADER = (
    "# Generated by firebreak lab render-config from the pinned demo's\n"
    "# Prometheus configuration. Do not edit. Change ops/alert_rules.yml or\n"
    "# src/firebreak/lab/stack.py instead.\n"
)


class StackConfigError(Exception):
    """The vendored configuration was not what this renderer expects."""


def build_prometheus_config(vendored: dict[str, Any]) -> dict[str, Any]:
    """Add Firebreak's rule file and Alertmanager target to the demo's config."""
    if not isinstance(vendored, dict) or "global" not in vendored:
        raise StackConfigError("vendored Prometheus config has no 'global' section")
    rendered = dict(vendored)
    rendered["rule_files"] = [RULE_FILE_IN_CONTAINER]
    rendered["alerting"] = {
        "alertmanagers": [{"static_configs": [{"targets": [ALERTMANAGER_TARGET]}]}]
    }
    return rendered


def render_prometheus_config(source: Path, destination: Path) -> Path:
    """Read the vendored Prometheus config and write Firebreak's version."""
    if not source.is_file():
        raise StackConfigError(f"vendored Prometheus config not found at {source}")
    vendored = yaml.safe_load(source.read_text(encoding="utf-8"))
    rendered = build_prometheus_config(vendored)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        GENERATED_HEADER + yaml.safe_dump(rendered, sort_keys=False),
        encoding="utf-8",
    )
    return destination
