"""The hygiene check must know about every kind of text file this repository tracks.

**The defect this closes.** `config/repo_hygiene.yaml` lists the extensions the dash and
filler-word checks scan. Phase 12 added a Quarto site, five `.qmd` pages and a `.scss` theme, and
neither extension was on the list. The check reported "clean" across five published pages that
contained en dashes, and the thing that caught them was an unrelated test in the site suite.

A gatekeeper whose vocabulary is a hand-maintained list will fall behind the repository. So
rather than adding the two extensions and moving on, this asserts the list covers what is
actually tracked, which makes the next new file type a failing test instead of a silent gap.

**Why an allowlist of exemptions rather than a wider default.** Some tracked text is not ours to
style: a vendored file, a lock file, a fixture that is deliberately malformed. Each exemption is
named here with its reason, so "not scanned" is a decision somebody wrote down.
"""

from __future__ import annotations

import subprocess
from collections import Counter
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "config" / "repo_hygiene.yaml"

# Extensions that hold text and are deliberately not scanned, each with the reason.
EXEMPT = {
    # Generated by uv. Not written by hand, and rewriting it to satisfy a style rule would
    # invalidate the hashes it exists to carry.
    ".lock",
    # Git's own metadata for the pinned submodule.
    ".gitmodules",
    # A licence is quoted verbatim. Editing punctuation in it would change its legal text.
    ".license",
}

# Files whose extension is scanned in general but which are exempt individually. Kept empty on
# purpose: an entry here is a file allowed to break the rules, and none should need to be.
EXEMPT_FILES: set[str] = set()

# Below this many tracked files, an extension is probably incidental rather than a file type the
# project writes in. A single stray `.bat` should not force a config change.
MINIMUM_TO_MATTER = 2


def tracked_files() -> list[str]:
    completed = subprocess.run(
        ("git", "ls-files"), cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )
    if completed.returncode != 0:
        pytest.skip("not a git checkout")
    return [line for line in completed.stdout.splitlines() if line]


def configured_extensions() -> set[str]:
    raw = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    return set(raw["text_extensions"])


def text_extensions_in_use() -> Counter[str]:
    """Tracked extensions that plausibly hold prose or code, by count.

    Judged by decoding rather than by a list of known suffixes, because the point is to notice a
    type nobody thought about. A file that decodes as UTF-8 and is not in `vendor/` is a file
    somebody wrote.
    """
    counts: Counter[str] = Counter()
    for relative in tracked_files():
        path = Path(relative)
        if path.parts and path.parts[0] == "vendor":
            continue
        suffix = path.suffix.lower()
        if not suffix or suffix in EXEMPT or relative in EXEMPT_FILES:
            continue
        full = REPO_ROOT / relative
        if not full.is_file():
            continue
        try:
            full.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        counts[suffix] += 1
    return counts


class TestTheConfigCoversWhatIsTracked:
    def test_every_text_extension_in_use_is_scanned(self) -> None:
        """The assertion that makes this file worth having. `.qmd` and `.scss` were missing and
        the check reported clean over five pages that broke its own rule."""
        configured = configured_extensions()
        in_use = text_extensions_in_use()
        missing = sorted(
            suffix
            for suffix, count in in_use.items()
            if suffix not in configured and count >= MINIMUM_TO_MATTER
        )
        assert not missing, (
            f"these tracked text types are not scanned by the hygiene check: {missing}. "
            "Add them to config/repo_hygiene.yaml text_extensions, or name them in EXEMPT here "
            "with the reason."
        )

    def test_the_scan_is_not_vacuous(self) -> None:
        """A `git ls-files` that returned nothing would make the test above pass while checking
        nothing, which is how a test built on tooling stops testing."""
        assert len(tracked_files()) > 100

    def test_the_new_extensions_are_listed(self) -> None:
        """Pinned by name, because the general check above tolerates a type with one file and
        these two are the ones that were actually missed."""
        configured = configured_extensions()
        assert ".qmd" in configured
        assert ".scss" in configured

    def test_every_configured_extension_starts_with_a_dot(self) -> None:
        """`Path.suffix` includes the dot, so an entry without one matches nothing and silently
        scans no files."""
        for suffix in configured_extensions():
            assert suffix.startswith("."), f"{suffix!r} will never match a Path.suffix"

    def test_every_configured_extension_is_lower_case(self) -> None:
        """The comparison is exact, so `.MD` would scan nothing."""
        for suffix in configured_extensions():
            assert suffix == suffix.lower()


class TestTheCheckActuallyRunsOverTheNewPages:
    def test_a_dash_in_a_qmd_file_is_caught(self, tmp_path: Path) -> None:
        """End to end over the real checker, because listing an extension in a config proves the
        list changed rather than that the scan reaches the file."""
        import importlib.util
        import sys

        spec = importlib.util.spec_from_file_location(
            "hygiene_under_test", REPO_ROOT / "scripts" / "check_repo_hygiene.py"
        )
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        assert module.is_text_file("explainer/index.qmd", sorted(configured_extensions()))
        assert module.is_text_file("explainer/custom.scss", sorted(configured_extensions()))

    def test_the_explainer_pages_are_tracked_and_therefore_scanned(self) -> None:
        tracked = set(tracked_files())
        pages = [f"explainer/{p.name}" for p in sorted((REPO_ROOT / "explainer").glob("*.qmd"))]
        assert pages, "no explainer pages found"
        untracked = [page for page in pages if page not in tracked]
        assert not untracked, f"these pages are not committed, so nothing scans them: {untracked}"
